### ISSUE TITLE
Budget item for qgis.org website refresh

### ISSUE THREAD

**Issue by pcav** [qgis/PSC#13]
Website needs a refresh, updates for cookies etc.

**Comment by andreasneumann** [comment]
Any idea how much is needed for this and who could work on this - @pcav ?

**Comment by pcav** [comment]
No idea about the amount. I guess the work can be split in two:
* update the infrastructure, adding warning for cookies, possibly moving to a different framework
* revising and refreshing the content - apparently many people find the current navigation structure a bit confusing.
Better discussing this in the next PSC.

**Comment by andreasneumann** [comment]
OK - we need to have a clear list of things we like to be addressed (your items above already help a bit). Otherwise we can't do an estimate and find the appropriate people to work on it.

Let's put it on the agenda of the next PSC meeting.

**Comment by andreasneumann** [comment]
Link to 2020 budget proposal:
https://docs.google.com/spreadsheets/d/1pUlUWa7PfgxLn-sX6K2ccPN7ZWXzqrw_QNNFyvw8Sl4/edit#gid=0

**Comment by mbernasocchi** [comment]
this is being worked on
