### ISSUE TITLE
Investing our profits from the training certificates

### ISSUE THREAD

**Issue by pcav** [qgis/PSC#14]
It would be useful to re-invest that money into improving training material and try to lobby universities to use more FOSSGIS in their curricula (perhaps starting from next year). Consult with Kurt and Hans on this matter.

**Comment by pcav** [comment]
Wrote to H+K

**Comment by jvdkwast** [comment]
I think the profits from the certificates should first be invested in improving the platform as suggested in the meeting in Bucharest (https://github.com/qgis/QGIS/wiki/Ideas-for-improving-the-QGIS-certification-programme). After improving the platform we can reach out to universities.

**Comment by pcav** [comment]
@jvdkwast would you like to lead this effort?

**Comment by jvdkwast** [comment]
@pcav yes I'm happy to do that.

**Comment by pcav** [comment]
Great, thanks. Please go ahead, and keep me in the loop.

**Comment by andreasneumann** [comment]
Needs a written proposal from the involved people (Tim, Kurt, Hans, myself)

**Comment by anitagraser** [comment]
We have a professional doc writer now
