### ISSUE TITLE
Filling vacant PSC seat: call for nominations

### ISSUE THREAD

**Issue by pcav** [qgis/PSC#15]
seat and organize election see: https://docs.google.com/forms/d/1BwB7I34xf21R6pyoAIVHpdoc-_7AY5phAnq7k7BwcPg/edit#responses
No new country user groups → no new voting members
Proposed to combine general PSC nominations with electing replacement for Richard

**Comment by mbernasocchi** [comment]
Ready for sending at: https://docs.google.com/forms/d/1PRvPVNlMOuiApsdIFxTFiPX_ZWTqV93LgytJ9e1JQpQ/edit
