### ISSUE TITLE
Formalize responsibilities and add deadlines to the PSC calendar

### ISSUE THREAD

**Issue by pcav** [qgis/PSC#16]
Current responsibilities:

Grant planning: Anita
Grant assessment / payments: Andreas
Grant reporting: Anita
Hackfest travel grant requests: Andreas
Hackfest travel reporting from grantees: Tim (chase)
Funded bugfix planning: Andreas
Funded bugfix reporting (changelog): Andreas
Specific funding requests: PSC vote
Specific funding feedback: Funded prerequisite should reporting on the work done and pass Tim to feed onto the blog
Community management: Marco
Votes: Marco
Github: Marco/Tim

**Comment by mbernasocchi** [comment]
@pcav what is to be done here?

**Comment by pcav** [comment]
This is an ongoing process. First we have to fix the past jobs, then we can add to the calendar the deadlines for publishing the reports.

**Comment by mbernasocchi** [comment]
is this still ongoing?

**Comment by anitagraser** [comment]
See QGIS.ORG calendar in https://docs.google.com/document/d/17N9j6s7IWZIzxPJXZbgo2z1qADWrOu6Avt7DIN8rFVk/edit?usp=sharing
