### ISSUE TITLE
Publish outcomes of the 2019 grant proposals

### ISSUE THREAD

**Issue by pcav** [qgis/PSC#21]
BUT multiple proposals have not finished yet

**Comment by nyalldawson** [comment]
For reference, the summary of work done for my two grants is here: https://lists.osgeo.org/pipermail/qgis-psc/2019-December/007960.html

**Comment by pcav** [comment]
Thanks @nyalldawson

**Comment by anitagraser** [comment]
For reference: six proposals were selected, checkmarks indicate received reports:

- [x] Vector rendering code (Nyall Dawson) https://lists.osgeo.org/pipermail/qgis-psc/2019-December/007960.html
- [x] Labeling engine (Nyall Dawson) https://lists.osgeo.org/pipermail/qgis-psc/2019-December/007960.html
- [x] DB manager (Alessandro Pasotti @elpaso & Nyall Dawson) https://www.itopen.it/qgis-abstract-connections-api/
- [x] Snapping (Hugo Mercier @mhugo) https://lists.osgeo.org/pipermail/qgis-psc/2020-January/008126.html
- [x] 3D (Martin Dobias @wonder-sk) https://lists.osgeo.org/pipermail/qgis-psc/2020-January/008158.html
- [x] Documentation issues (Matthias Kuhn @m-kuhn and Denis Rouzaud @3nids) https://lists.osgeo.org/pipermail/qgis-psc/2020-January/008095.html

**Comment by anitagraser** [comment]
Related issue; https://github.com/qgis/PSC/issues/8

**Comment by anitagraser** [comment]
@elpaso and @mhugo: Since your proposals are already implemented, please provide a summary of the grant work that can be used in a report (blog post) on the grant programme.

**Comment by m-kuhn** [comment]
>  Documentation issues (Matthias Kuhn @m-kuhn)

Denis Rouzaud (@3nids) was / is actively working on this.

**Comment by troopa81** [comment]
@anitagraser Regarding snapping, I will prepare a blog post by the end of the week

**Comment by elpaso** [comment]
@anitagraser I'll write a summary and share a google doc with you, is that ok?

**Comment by 3nids** [comment]
@anitagraser here we go https://lists.osgeo.org/pipermail/qgis-psc/2020-January/008095.html

**Comment by anitagraser** [comment]
@3nids Thank you! I've updated the list.

**Comment by anitagraser** [comment]
@elpaso Are you planning to publish your document somewhere (e.g. on a blog)? It's quite long and I'll only be able to include some core infos in the overview report.

**Comment by troopa81** [comment]
@anitagraser here is my report https://lists.osgeo.org/pipermail/qgis-psc/2020-January/008126.html

**Comment by wonder-sk** [comment]
Adding my report https://lists.osgeo.org/pipermail/qgis-psc/2020-January/008158.html

**Comment by anitagraser** [comment]
@elpaso Could you also publish your information somewhere? 

> Are you planning to publish your document somewhere (e.g. on a blog)? It's quite long and I'll only be able to include some core infos in the overview report.

**Comment by elpaso** [comment]
@anitagraser done: https://www.itopen.it/qgis-abstract-connections-api/

**Comment by anitagraser** [comment]
Thanks everyone! We now have completed collecting the reports and I'll publish a corresponding summary post on blog.qgis.org in the near future that will link to your detailed reports.

**Comment by 3nids** [comment]
thanks a lot @anitagraser 
before running the next round, may I suggest to review the different discussions we had?
mainly the requirement of having a QEP per proposal to allow discussing them.

**Comment by anitagraser** [comment]
@3nids Thank you for the reminder! I'll create a separate ticket for this.

**Comment by anitagraser** [comment]
@3nids please see https://github.com/qgis/PSC/issues/31

**Comment by anitagraser** [comment]
Published http://blog.qgis.org/2020/02/23/reports-from-the-winning-grant-proposals-2019/

Thanks everyone for helping collect the necessary info!

**Comment by pcav** [comment]
Thank you Anita!
