### ISSUE TITLE
 Incubation process for projects such as QField, INPUT, Roam

### ISSUE THREAD

**Issue by pcav** [qgis/PSC#23]
Saber also suggests to have an (OSGeo) incubation process for projects such as QField, INPUT, Roam to be accredited as ‘official’ projects
The group agreed that this needs broader discussion before making a decision 
TODO take it to the mailing list
Do we want to discuss first and suggest 1 or 2 proposals? I see infinite mailings on this
How about a QEP - good mechanism for this?
Yep or first an ad-hoc meeting to get started. I prefer discussing :)

**Comment by haubourg** [comment]
Good idea. We should discuss what are requirements of an incubation project and a official project are. 

the OSGEO incubation page is interesting to start discussing : https://wiki.osgeo.org/wiki/Incubation_FAQ

**Comment by pcav** [comment]
Apparently the options are:
* each project as a separate OSGeo project
* all under QGIS umbrella
* and of course option 0, leave everything as it is.
There are of course advantages and disadvantages of each solution. Leaders of each project will have the last work here.

**Comment by luipir** [comment]
should be extended to qgis server clients too? or it's limited to mobile clients?

**Comment by pcav** [comment]
Agreed, a similar process would make sense for web clients as well, IMHO. The original request came from mobile clients, however, so let's start from here.
Thanks for the suggestion.

**Comment by haubourg** [comment]
IMO, we should be able to list all serious QGIS related project. 
But I would treat differently projects that aim to become free communities - with the same requirement as OSGEO project (PSC, code of conduct, governance rules, etc..) and the projects that are very linked to an editor.
The OSGEO requires a open PSC with elections to recognize a osgeo project for instance, which leads have OSGEO4W not being a valid project for instance (ironically). They propose community projects for the associated project not matching the full requirements.

 I think most QGIS related projects are in this category currently. Maybe QWC2 is more a multi editor project and could go towards having a PSC.

**Comment by NathanW2** [comment]
Thanks @pcav.  I would be keen to have a chat about Roam in this kind of thing.

**Comment by andreasneumann** [comment]
I think there should be both options available: incubate at OSGeo or at QGIS - with or without a PSC. In the latter case, QGIS PSC could potentially step in. I would let the team of the project decide how they want to organize.

In case of "incubation" at QGIS.ORG, the QGIS code of conduct should automatically be applied to the project under the hood of the QGIS organization.

**Comment by pcav** [comment]
@NathanW2 thanks. we have the choice of either setting up a voice meeting or a discussion on the mailing list. Feel free to propose the solution that suits you better.

**Comment by anitagraser** [comment]
@haubourg would you say that we can close this issue? or is there still an open todo?

**Comment by haubourg** [comment]
Well yes I think we are still in a status quo where we will always have a fuzzy border going from open core to free software. 
Having a catalog like we have in overview page seems good enough to me. Affiliated project can always follow an osgeo incubation process without QGIS.org having to rule its own incubation process
