### ISSUE TITLE
Publish QGIS.ORG Annual Report 2019

### ISSUE THREAD

**Issue by anitagraser** [qgis/PSC#28]
Deadline
===========
2020-01-31

Notes
=====
Last year's report for reference: https://docs.google.com/document/d/114ofo3juxXFCKPVBqFuYIz8MB1xhBdXifo9e54V7ovU/edit?usp=sharing

**Comment by anitagraser** [comment]
New document: https://docs.google.com/document/d/1_Jk2VK3ntRKIjMIFxotu8fzJ2hfM4Xr3k2jD-YndM-s/edit?usp=sharing

**Comment by anitagraser** [comment]
@pcav I've update the report with the 2019 information. Please check and add any relevant information I might have missed.

**Comment by pcav** [comment]
Thanks a lot @anitagraser . I have read it, checked, made minor adjustments, and I believe it is OK.
Don't we have any report for the Bucharest CM?

**Comment by anitagraser** [comment]
Thank you @pcav! About Bucharest CM: There's no report on http://blog.qgis.org and I didn't attend but maybe someone who did can write a short summary?

**Comment by pcav** [comment]
Maybe it does not make much sense so long after. @timlinux do you have anything?

**Comment by anitagraser** [comment]
Maybe this should be open until the PDF version has been published on the website. 

https://qgis.org/en/site/getinvolved/governance/annual_reports/index.html

**Comment by anitagraser** [comment]
@pcav maybe you want to publish it on the website, since the document is signed in your name

**Comment by pcav** [comment]
OK, will do ASAP

**Comment by pcav** [comment]
for ref: https://github.com/qgis/QGIS-Website/blob/master/source/site/getinvolved/governance/annual_reports/index.rst

**Comment by pcav** [comment]
Done, thanks again.
