### ISSUE TITLE
QGIS Server docker in official QGIS hub repo

### ISSUE THREAD

**Issue by pcav** [qgis/PSC#3]
FROM OLD psc MEETING:

Status: there are multiple docker containers out there but no official one from QGIS. https://hub.docker.com/search?q=qgis-server&type=image 
There is a good one by ???Gem???. Marco could ask them to make their work the official one.
TODO: Marco to ask current maintainers of different images if they would be prepared to maintain an official image. We should explain that we are planning to select between the popular docker server images and that they may not be the successful one.

**Comment by mbernasocchi** [comment]
Oslandia, GEM and 3Liz (partially) are interested in having their image used. 3Liz says their image might be a bit too complex.
A project might happen in Switzerland that would dedicate lots of resources to this, so I suggest waiting and see what happens there to avoid duplication.

**Comment by anitagraser** [comment]
https://github.com/qgis/qgis-docker
