### ISSUE TITLE
Refine the grant proposal process

### ISSUE THREAD

**Issue by anitagraser** [qgis/PSC#31]
Deadline
===========
2020-02-28

Notes
=====
In response to last years' rounds of grants, ideas for improving our grants process have been raised. They include:

1. 2018 thread: http://osgeo-org.1560.x6.nabble.com/Grant-application-suggestions-for-next-time-td5368078.html
2. 2019 thread: http://osgeo-org.1560.x6.nabble.com/QGIS-Developer-grant-proposal-tp5408848.html

TODO: 
* [x] Summarize the suggestions
* [x] Discuss the suggestions and find consensus 
* [x] Publish the outcome

**Comment by anitagraser** [comment]
Suggestions:

1. Create a new github repo for submission of the grant proposals (by @nyalldawson http://osgeo-org.1560.x6.nabble.com/Grant-application-suggestions-for-next-time-tp5368078.html)
2. Require that code-related proposals be accompanied by a QEP filed at least xx days in advance of the grant application (by @nyalldawson http://osgeo-org.1560.x6.nabble.com/Grant-application-suggestions-for-next-time-tp5368078.html also suggested by @3nids in http://osgeo-org.1560.x6.nabble.com/QGIS-Developer-grant-proposal-tp5408848.html)
3. Require a definition on what is to be the 'end product'. That is something written what can be used to check if the proposal is finished or not. (by @rduivenvoorde http://osgeo-org.1560.x6.nabble.com/Grant-application-suggestions-for-next-time-tp5368078p5368507.html)

Questions:

a. Should PSC provide reommendations? Should voting members who also submitted proposals themselves be allowed to vote on them? (raised by @3nids in http://osgeo-org.1560.x6.nabble.com/QGIS-Developer-grant-proposal-tp5408848.html)

**Comment by nyalldawson** [comment]
> Should PSC provide reommendations?

I think at the least the PSC should have "veto" power over submissions. E.g. if the call for grants specifically states that no new feature proposals are permitted (not sure if that's the plan for this year or not, but just using it as an example), then any proposals which are clearly new features should be filtered out by PSC prior to public listing of the proposals.

**Comment by pcav** [comment]
I think proposal should be examined by PSC, and refused if not compliant with general policy, as Nyall suggested. Furthermore, I believe PSC recommendations will be good to have, and appreciated.

**Comment by 3nids** [comment]
Thanks a lot @anitagraser for the summary.

I have the feeling that voting members don't receive sufficient information to make the vote. If we stick to infrastructure and refactoring grants, it's usually quite low level and it's hard to have a good picture.
Having recommendations from the PSC sounds a bit risky but I think it is worth at least discussing the idea.

A softer approach would be this: at the end of the discussion phases on the QEPs, a short summary of the comments (5 lines) for each QEP is made (by PSC? by the author?). For the vote, the short description of the QEP + short comments summary is sent for voting.
That would make a nice dashboard to vote on.

**Comment by m-kuhn** [comment]
Having a veto power for the PSC is a good idea.
It's a powerful tool and as such when used it risks damaging relations and political good will.

(Not only) therefore I second @3nids proposal. I would recommend that the summary is written by the PSC (or an appointed other entity) and explicitly not by the author of the grant proposal. The author himself already has the platform to promote his ideas in the grant itself and the summary should act as a balance.

> Should voting members who also submitted proposals themselves be allowed to vote on them?

Yes, I think they should.

**Comment by timlinux** [comment]
> I think at the least the PSC should have "veto" power over submissions. E.g. if the call for grants specifically states that no new feature proposals are permitted (not sure if that's the plan for this year or not, but just using it as an example), then any proposals which are clearly new features should be filtered out by PSC prior to public listing of the proposals.

So I think veto power is a different thing than what you describe above. From your description above, it is a simple screening of proposals for eligibility (which I agree with).

Veto implies that a proposal makes it into voting, is voted for and then we veto an otherwise validly selected proposal (which I am not sure would be a good thing).

**Comment by nyalldawson** [comment]
@timlinux ok - to clarify i meant the "filter-the-entries-before-voting-opens" power.

**Comment by pcav** [comment]
Agreed with Tim.

**Comment by 3nids** [comment]
I would like to precise the idea of the discussion + summary:

During the discussion time-frame (after submission dead-line and before voting), people are invited to discuss on the QEP about concerns, opportunities and ask for more precision. At the end of the discussions, one or several persons will be in charge of writing summaries of the discussions, which will be appended to the QEP description body. 
When calling for vote, a 4-8 lines description of each proposal with its summary of the discussion is sent to the voters. Hence there will be one "small" document which will allow people to vote with more knowledge (for those which not go through all the QEPs).

**Comment by anitagraser** [comment]
@3nids Thanks!

> When calling for vote, a 4-8 lines description of each proposal with its summary of the discussion is sent to the voters. 

So the document for voters should contain 4-8 lines + discussion summary for each proposal? 

> one or several persons will be in charge of writing summaries of the discussions

Who should be in charge?

**Comment by 3nids** [comment]
Yes, proposal summary and discussion summary would be sent at once.

It could be either someone from the PSC or from the community. If not soneone from the PSC, it could be spread over 2 devs if they have some interest in the proposals.

**Comment by anitagraser** [comment]
@mbernasocchi @pcav @timlinux @jef-n @andreasneumann Does any one of you want to volunteer?

**Comment by pcav** [comment]
If nobody else is available I can take this.

**Comment by anitagraser** [comment]
@pcav We should update the existing documentation of the grant process to reflect the discussed changes: https://docs.google.com/document/d/1CNmSJxztrHrqLfillDH8v1zWaMzxFUyYSPT3sut55eQ/edit?usp=sharing 

In particular, it includes the text for the form that was used to submit proposals. This will have to be updated.

The document is also open for further comments (everyone with the link should be able to comment).

Thanks for offering to help!

**Comment by pcav** [comment]
Please check the edits. I think most needed info should be present now.
Cheers.

**Comment by anitagraser** [comment]
@nyalldawson @3nids @m-kuhn @timlinux Please have a look at the document if you can so we can finalize and vote on it in the next PSC meeting on Tuesday.

**Comment by anitagraser** [comment]
I'm wondering about the time line. Currently, our document states

> Code-related proposals must be accompanied by a QEP filed at least 10 days in advance of the grant application 

Is this helpful? Or should we instead have some time (e.g. two weeks) between grant submission deadline and starting the voting?

**Comment by pcav** [comment]
@anitagraser your proposal makes sense to me. I leave comments to the original proponent of the 10-days advance, I believe @nyalldawson

**Comment by anitagraser** [comment]
We've voted on the new process: https://lists.osgeo.org/pipermail/qgis-psc/2020-April/008639.html

The call for grant proposals has been published on 2020-04-26
http://blog.qgis.org/2020/04/26/qgis-grants-5-call-for-grant-proposals-2020/

**Comment by anitagraser** [comment]
Thanks to @3nids for compiling the summary of this year's eligible grants:  https://lists.osgeo.org/pipermail/qgis-psc/2020-June/008897.html 

Comments welcome (here or on the mailing list)!
