### ISSUE TITLE
We need an environmental policy

### ISSUE THREAD

**Issue by timlinux** [qgis/PSC#36]
Deadline
===========
2020-12-12

**Environmental policy**
* Similar to Diversity statement 
* Should be added near the code of conduct
* Not part of the charter → Doesn’t need to go through AGM
* Andreas: suggestion to use 1000km aerial distance for a decision to take the train or not
* Also when deciding for contributor meetings we should pick places where many people don’t have to fly
* People should do a CO2 compensation for their flights through organizations like MyClimate ( https://www.myclimate.org/de/ ) or similar
* Consider doing parallel contributor meetings in other continents and only one physical meeting per year
* TODO Andreas & Tim to draft Environmental Policy

**Comment by andreasneumann** [comment]
Done. Accepted at the AGM 2020.
