### ISSUE TITLE
Reports from the winning grant proposals 2020

### ISSUE THREAD

**Issue by anitagraser** [qgis/PSC#43]
**[Published blog post](https://blog.qgis.org/2021/04/03/reports-from-the-winning-grant-proposals-2020/)**

Status of individual project reports:

- [x] https://github.com/qgis/QGIS-Enhancement-Proposals/issues/180 - [Report](https://lists.osgeo.org/pipermail/qgis-psc/2020-December/009186.html)
- [x] https://github.com/qgis/QGIS-Enhancement-Proposals/issues/181 - [Report](https://lists.osgeo.org/pipermail/qgis-psc/2021-January/009211.html)
- [x] https://github.com/qgis/QGIS-Enhancement-Proposals/issues/171 - [Report](https://lists.osgeo.org/pipermail/qgis-psc/2020-September/009084.html)
- [x] https://github.com/qgis/QGIS-Enhancement-Proposals/issues/175 - [Report](https://lists.osgeo.org/pipermail/qgis-psc/2020-November/009144.html)
- [x] https://github.com/qgis/QGIS-Enhancement-Proposals/issues/163 (followed up by https://github.com/qgis/QGIS-Enhancement-Proposals/issues/237) - [Report](https://lists.osgeo.org/pipermail/qgis-psc/2021-October/009535.html)
- [x] https://github.com/qgis/QGIS-Enhancement-Proposals/issues/185 - [Report](https://lists.osgeo.org/pipermail/qgis-psc/2020-November/009146.html)
- [x] https://github.com/qgis/QGIS-Enhancement-Proposals/issues/172 - [Report](https://lists.osgeo.org/pipermail/qgis-psc/2020-September/009078.html)
- [x] https://github.com/qgis/QGIS-Enhancement-Proposals/issues/186
- [x] https://github.com/qgis/QGIS-Enhancement-Proposals/issues/124 - [Report](https://lists.osgeo.org/pipermail/qgis-psc/2022-January/009670.html)
- [x] https://github.com/qgis/QGIS-Enhancement-Proposals/issues/177 - [Report](https://lists.osgeo.org/pipermail/qgis-psc/2020-September/009074.html)

**Comment by anitagraser** [comment]
If I haven't missed any reports, it seems that five projects are still outstanding:

* https://github.com/qgis/QGIS-Enhancement-Proposals/issues/180 (@SrNetoChan)
* https://github.com/qgis/QGIS-Enhancement-Proposals/issues/181 (@wonder-sk)
* https://github.com/qgis/QGIS-Enhancement-Proposals/issues/163 (@3nids)
* https://github.com/qgis/QGIS-Enhancement-Proposals/issues/186 (@mhugo)
* https://github.com/qgis/QGIS-Enhancement-Proposals/issues/124 (@3nids)

**Comment by SrNetoChan** [comment]
@anitagraser We made our report in December. 

https://lists.osgeo.org/pipermail/qgis-psc/2020-December/009186.html

Nevertheless, we will keep working on adding a few more example test cases, and we plan to put the structure and methods to practice for 3.18 and 3.16LTR releases.

**Comment by wonder-sk** [comment]
Report for QEP#181: https://lists.osgeo.org/pipermail/qgis-psc/2021-January/009211.html

**Comment by anitagraser** [comment]
We will be wrapping up the annual report soon and would like to include the grant proposal reports (like last year, there will be a link to [the blog post](https://blog.qgis.org/2020/02/23/reports-from-the-winning-grant-proposals-2019/)). @3nids and @mhugo could you provide status reports by mid of March? 

Reports from these three projects are currently outstanding:

* https://github.com/qgis/QGIS-Enhancement-Proposals/issues/163 (@3nids)
* https://github.com/qgis/QGIS-Enhancement-Proposals/issues/186 (@mhugo)
* https://github.com/qgis/QGIS-Enhancement-Proposals/issues/124 (@3nids)

**Comment by vpicavet** [comment]
As for https://github.com/qgis/QGIS-Enhancement-Proposals/issues/186 we are still looking for a review and it is not easy. We are working on it with Andreas, and we will keep you updated on the status as soon as we have visibility on the outcome.

**Comment by anitagraser** [comment]
I've published the blog post summarizing the currently available 7 reports: https://blog.qgis.org/2021/04/03/reports-from-the-winning-grant-proposals-2020/

The blog post will be updated with further reports as they come in.

**Comment by anitagraser** [comment]
Hi @3nids and @mhugo, could you please let me know about the status of the three outstanding project reports? It would be great to be able to close this ticket.

**Comment by 3nids** [comment]
I sent it to PSC mailing list https://lists.osgeo.org/pipermail/qgis-psc/2021-October/009535.html
You can find the final report as a QEP here: https://github.com/qgis/QGIS-Enhancement-Proposals/issues/237

**Comment by anitagraser** [comment]
Thank you for the fast response, @3nids! Do you also have an update for https://github.com/qgis/QGIS-Enhancement-Proposals/issues/124 ?

**Comment by anitagraser** [comment]
@obrix have you been working on https://github.com/qgis/QGIS-Enhancement-Proposals/issues/186 ?

**Comment by 3nids** [comment]
> Thank you for the fast response, @3nids! Do you also have an update for qgis/QGIS-Enhancement-Proposals#124 ?

Sorry for this, I will send a report in the next days.

**Comment by obrix** [comment]
@anitagraser  Yes but I have not been in charge of this work for a while. It seems @troopa81 is in charge now, see last message on https://github.com/qgis/QGIS-Enhancement-Proposals/issues/186

**Comment by troopa81** [comment]
@anitagraser I resumed the work started by @obrix and I am on the edge of releasing something, but there is still work to be done. The report will follow then. Sorry for the (great) delay

**Comment by 3nids** [comment]
I just added the report for the setting registry: https://github.com/qgis/QGIS-Enhancement-Proposals/issues/124#issuecomment-1020119026

**Comment by anitagraser** [comment]
Thank you @3nids . I've updated the blog post to include your reports: https://blog.qgis.org/2021/04/03/reports-from-the-winning-grant-proposals-2020/

**Comment by troopa81** [comment]
I've just sent report for the vectorization of selective masking : https://lists.osgeo.org/pipermail/qgis-psc/2022-May/009772.html
