### ISSUE TITLE
Write 32bit news item

### ISSUE THREAD

**Issue by anitagraser** [qgis/PSC#44]
Deadline
===========
2020-10-30

Notes
=====
https://docs.google.com/document/d/1Im-Z83byy1Wz93yd_v91TtkMxhMnsaHUkXwXXDpP924/edit?usp=sharing

**Comment by mbernasocchi** [comment]
@anitagraser did you receive my bulletpoints last week?

**Comment by anitagraser** [comment]
@mbernasocchi No, I didn't. Was it a google docs invite?

**Comment by mbernasocchi** [comment]
@anitagraser I shared it again to your @qgis address

**Comment by anitagraser** [comment]
Let me know if the draft works for you and then we can mail and blog it.

**Comment by mbernasocchi** [comment]
thanks a lot was perfect, I've published the blog. will do the mailing now. 
can you tweet?

**Comment by andreasneumann** [comment]
![image](https://user-images.githubusercontent.com/884476/96084231-05931600-0ebf-11eb-8acc-0ec1b0de938f.png)

Is this some abbreviation / slang thing that I don't know, or an error?

**Comment by andreasneumann** [comment]
Apparently "Tl;dr" stands fro "too long; didn't read" is it this what you mean?

See https://www.howtogeek.com/435266/what-does-tldr-mean-and-how-do-you-use-it/

**Comment by mbernasocchi** [comment]
yes, it is pretty commonly used in blogs

**Comment by mbernasocchi** [comment]
@andreasneumann normally it should not be in an excerpt. I removed it now from the excerpt, and left it in the post
thanks for reporting

**Comment by anitagraser** [comment]
Done: https://twitter.com/qgis/status/1316634157360074752

**Comment by andreasneumann** [comment]
> yes, it is pretty commonly used in blogs

And you actually mean that? Too long, didn't read? I have no idea what this should mean in this context. The blog entry is really short - so I have no idea what this should mean in this context.

**Comment by mbernasocchi** [comment]
if you look at the blogpost, the tl;dr ist 1 sentence that tells you what the content of the post is. same as an executive summary.

**Comment by andreasneumann** [comment]
Stupid thing in my opinion. Not everyone understands such abbreviations. To me it looks like an error - like someone didn't manage to write HTML correctly.

**Comment by anitagraser** [comment]
I was assuming that this abbreviation has become common knowledge online but since this doesn't seem to be the case, I've removed it from the blog post.

**Comment by andreasneumann** [comment]
> I was assuming that this abbreviation has become common knowledge online but since this doesn't seem to be the case, I've removed it from the blog post.

Well maybe I'm old fashioned - but I'm also approx. 10 years older than you guys ;-)

In any case - this blog post is so short that you don't really need a summary.

**Comment by andreasneumann** [comment]
Out of curiosity: I asked all of my coworkers if they knew this abbreviation - not a single person knew it.

But now that I've learned something new, I feel at least 5 years younger ;-)

**Comment by andreasneumann** [comment]
According to https://www.howtogeek.com/435266/what-does-tldr-mean-and-how-do-you-use-it/ you'd have to get rid of the semicolon - or you are outing yourselve as an "old" geek as well ;-)
