### ISSUE TITLE
Check real cost of OGC certification

### ISSUE THREAD

**Issue by anitagraser** [qgis/PSC#48]
Deadline
===========
2020-11-10

**Comment by anitagraser** [comment]
The costs are a function of

`QGIS version * Standard version * Protocol version * EUR 300 per year`

So, if we only certify LTR for the most recent standard version, we estimate yearly costs of EUR 600 for (WMS + WFS).

**Comment by mbernasocchi** [comment]
The decision is to do only for the current LT version for WMS, WFS, OAPIF (AKA wfs3) -> 900€/year
