### ISSUE TITLE
Update QGIS.org structure diagramm

### ISSUE THREAD

**Issue by mbernasocchi** [qgis/PSC#50]
The diagram of QGIS.org includes names and so on.

Ideally, it should only include role names so that it is always up to date and does not need maintenance.

for reference, talking about this: 
https://drive.google.com/file/d/12qPHUjvPv5CMpZKSWHwr65DG-YOZsub1/view?usp=sharing

**Comment by agiudiceandrea** [comment]
Hi @mbernasocchi, it seems to me the QGIS.org structure diagramm is already updated at https://www.qgis.org/en/site/getinvolved/governance/governance.html#who-is-who-in-the-project (only include role names).

Anyway, the info about the Board / PSC at https://www.qgis.org/en/site/getinvolved/governance/governance.html#board and the Community voting members https://www.qgis.org/en/site/getinvolved/governance/governance.html#community-voting-members seem not up to date.

**Comment by anitagraser** [comment]
Done
