### ISSUE TITLE
Reports from the winning grant proposals 2021

### ISSUE THREAD

**Issue by anitagraser** [qgis/PSC#56]
- [x] [Write up summary blog post](https://blog.qgis.org/2022/02/05/reports-from-the-winning-grant-proposals-2021/)

Deadline
===========
2022-01-31

Notes
=====

This TODO is part of #53.

Status of individual reports:

- [x] https://github.com/qgis/QGIS-Enhancement-Proposals/issues/213 - [Report](https://lists.osgeo.org/pipermail/qgis-psc/2022-January/009626.html)
- [x] https://github.com/qgis/QGIS-Enhancement-Proposals/issues/216 - [Report](https://lists.osgeo.org/pipermail/qgis-psc/2021-July/009429.html)
- [x] https://github.com/qgis/QGIS-Enhancement-Proposals/issues/205 - [Report](https://lists.osgeo.org/pipermail/qgis-psc/2021-August/009437.html)
- [x] https://github.com/qgis/QGIS-Enhancement-Proposals/issues/210 - [Report](https://lists.osgeo.org/pipermail/qgis-psc/2022-January/009622.html)
- [x] https://github.com/qgis/QGIS-Enhancement-Proposals/issues/217 - [Report](https://lists.osgeo.org/pipermail/qgis-psc/2021-August/009436.html)
- https://github.com/qgis/QGIS-Enhancement-Proposals/issues/219 - withdrawn
- [x] https://github.com/qgis/QGIS-Enhancement-Proposals/issues/212 - [Report](https://lists.osgeo.org/pipermail/qgis-psc/2022-January/009625.html)
- [x] https://github.com/qgis/QGIS-Enhancement-Proposals/issues/215 - [Report](https://lists.osgeo.org/pipermail/qgis-psc/2022-January/009621.html)

**Comment by elpaso** [comment]
Regarding https://github.com/qgis/QGIS-Enhancement-Proposals/issues/210

The work has been completed with multiple pull requests that fixed all localization issues that have been reported plus countless unreported issues that have been identified along the way.

Here is a list of the relevant pull requests:

Localization of feature count attr table titles https://github.com/qgis/QGIS/pull/46293
Fix qgsdoublevalidator group separator https://github.com/qgis/QGIS/pull/45777
Fix multiple localization issues with vector renderers https://github.com/qgis/QGIS/pull/45587
Fixes custom ellipsoid locale double input https://github.com/qgis/QGIS/pull/45076
GUI localization tweaks https://github.com/qgis/QGIS/pull/43831
Remove duplicated code for localized numbers https://github.com/qgis/QGIS/pull/43804
Coordinate formatter localization https://github.com/qgis/QGIS/pull/43756
Localization for table layout items https://github.com/qgis/QGIS/pull/43705
Localize numbers in expression preview https://github.com/qgis/QGIS/pull/43699

**Comment by anitagraser** [comment]
@elpaso excellent. Could you please also send the report to the PSC list (similar to https://lists.osgeo.org/pipermail/qgis-psc/2022-January/009621.html) so we have a permanent public record. Thanks!

**Comment by pblottiere** [comment]
Grant reports for:

- [QGIS Server and services documentation](https://github.com/qgis/QGIS-Enhancement-Proposals/issues/213): https://lists.osgeo.org/pipermail/qgis-psc/2022-January/009626.html
- [QGIS Server, OGC tests and Continuous Integration: OGC API Features (part 2)](https://github.com/qgis/QGIS-Enhancement-Proposals/issues/212): https://lists.osgeo.org/pipermail/qgis-psc/2022-January/009625.html
