### ISSUE TITLE
HANA provider

### ISSUE THREAD

**Issue by pcav** [qgis/PSC#6]
Reach a final decision.

**Comment by pcav** [comment]
Marco reports that there’s been a call with SAP but it’s not cleared up yet, they expect free development work

**Comment by mbernasocchi** [comment]
We are in discussion with SAP. They do _not_ expect free dev work.

**Comment by mbernasocchi** [comment]
Matthias is working with them to help getting all the requirements as needed. They already have implemented missing tests and are now working on CI.

**Comment by mbernasocchi** [comment]
Merged https://github.com/qgis/QGIS/pull/34988
