### ISSUE TITLE
Status of accepted Grants 2019

### ISSUE THREAD

**Issue by pcav** [qgis/PSC#8]
See https://drive.google.com/drive/u/0/folders/1DwFBOiTKI_ncoQF_GX7yGd21eTWbcDyU 
We should try to make sure they are completed and paid by the end of the year.
TODO: Andreas to ask devs about the status.
Accepted proposals and their status:
* Profile and optimise the QGIS vector rendering code (N. Dawson): done and paid
* "Rebalance" the labeling engine and fix poor automatic label placement choices  (N. Dawson): done and paid
* Reuse core functionality to provide DB manager features (A. Pasotti): done and paid
* Snapping cache improvements (H. Mercier): done and paid
* Fix problems in larger 3D scenes (M. Dobias): still in the works
* Open documentation issues for pull requests (OpenGIS): still in the works

**Comment by nyalldawson** [comment]
> Profile and optimise the QGIS vector rendering code (N. Dawson):
"Rebalance" the labeling engine and fix poor automatic label placement choices (N. Dawson)

These two are done and paid -- there's a final report here:

https://lists.osgeo.org/pipermail/qgis-psc/2019-December/007960.html

**Comment by pcav** [comment]
Thanks @nyalldawson

**Comment by andreasneumann** [comment]
I updated the status of the grants above. The last two are still being worked on.

**Comment by pcav** [comment]
Is this still useful?
