### ISSUE TITLE
Advertise Nødebo 2020 User Conference & Developer Meeting in news feed

### ISSUE THREAD

**Issue by pcav** [qgis/PSC#9]
Add next user question to https://feed.qgis.org/admin 
Add future blog.qgis.org posts 
Advertise developer / user meetings

**Comment by anitagraser** [comment]
As it currently stands, this issue is a reoccurring task that can never be closed. 
To change it to an issue that can be closed I'm focusing it on advertising the upcoming user conference https://github.com/qgis/QGIS/wiki/25th-Developer-Meeting-in-Nødebo,-Denmark

**Comment by anitagraser** [comment]
We'll start advertising this after the developer meeting.

**Comment by anitagraser** [comment]
The 2020 event in Nodebo had to be cancelled
